# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(619, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.maskfram = QtWidgets.QFrame(self.centralwidget)
        self.maskfram.setGeometry(QtCore.QRect(379, 0, 241, 251))
        self.maskfram.setStyleSheet("image: url(:/images/img.png);")
        self.maskfram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskfram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskfram.setObjectName("maskfram")
        self.mainbgftame = QtWidgets.QFrame(self.centralwidget)
        self.mainbgftame.setGeometry(QtCore.QRect(0, 80, 500, 400))
        self.mainbgftame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.165, x2:1, y2:0.449, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(1, 29, 63, 255));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.mainbgftame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbgftame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbgftame.setObjectName("mainbgftame")
        self.logoframe_2 = QtWidgets.QFrame(self.mainbgftame)
        self.logoframe_2.setGeometry(QtCore.QRect(0, -40, 231, 191))
        self.logoframe_2.setStyleSheet("image: url(:/images/face recog logo.png);\n"
"background-color:none;")
        self.logoframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoframe_2.setObjectName("logoframe_2")
        self.frame_2 = QtWidgets.QFrame(self.mainbgftame)
        self.frame_2.setGeometry(QtCore.QRect(-30, 130, 960, 650))
        self.frame_2.setStyleSheet("background-color:none;\n"
"border:16px solid  rgb(2, 108, 203);\n"
"\n"
"border-top-left-radius:160px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.employeebutton = QtWidgets.QPushButton(self.frame_2)
        self.employeebutton.setGeometry(QtCore.QRect(80, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.employeebutton.setFont(font)
        self.employeebutton.setStyleSheet("QPushButton#employeebutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#employeebutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#employeebutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        self.employeebutton.setObjectName("employeebutton")
        self.gethistorybutton = QtWidgets.QPushButton(self.frame_2)
        self.gethistorybutton.setGeometry(QtCore.QRect(310, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gethistorybutton.setFont(font)
        self.gethistorybutton.setStyleSheet("QPushButton#gethistorybutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#gethistorybutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#gethistorybutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        self.gethistorybutton.setCheckable(False)
        self.gethistorybutton.setObjectName("gethistorybutton")
        self.maskborderframe = QtWidgets.QFrame(self.centralwidget)
        self.maskborderframe.setGeometry(QtCore.QRect(370, 0, 250, 250))
        self.maskborderframe.setStyleSheet("border:5px solid  rgb(2, 108, 203);\n"
"background-color: qlineargradient(spread:pad, x1:0.0397727, y1:0.949, x2:0.841, y2:0.159682, stop:0 rgba(1, 29, 63, 176), stop:1 rgba(2, 108, 203, 0));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"")
        self.maskborderframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskborderframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskborderframe.setObjectName("maskborderframe")
        self.backbutton = QtWidgets.QPushButton(self.centralwidget)
        self.backbutton.setGeometry(QtCore.QRect(30, 20, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backbutton.sizePolicy().hasHeightForWidth())
        self.backbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.backbutton.setFont(font)
        self.backbutton.setStyleSheet("QPushButton#backbutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#backbutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#backbutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("back.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.backbutton.setIcon(icon)
        self.backbutton.setObjectName("backbutton")
        self.maskborderframe.raise_()
        self.mainbgftame.raise_()
        self.maskfram.raise_()
        self.backbutton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADMIN"))
        self.employeebutton.setText(_translate("MainWindow", "Add New Employee"))
        self.gethistorybutton.setText(_translate("MainWindow", "Login/Logout History"))
        self.backbutton.setText(_translate("MainWindow", "BACK"))
import recogapp_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())