# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Doc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(960, 650)
        main.setMinimumSize(QtCore.QSize(960, 650))
        main.setMaximumSize(QtCore.QSize(960, 650))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setStyleSheet("")
        self.maskborderframe = QtWidgets.QFrame(main)
        self.maskborderframe.setGeometry(QtCore.QRect(480, 0, 480, 321))
        self.maskborderframe.setStyleSheet("border:5px solid  rgb(2, 108, 203);\n"
"background-color: qlineargradient(spread:pad, x1:0.0397727, y1:0.949, x2:0.841, y2:0.159682, stop:0 rgba(1, 29, 63, 176), stop:1 rgba(2, 108, 203, 0));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"")
        self.maskborderframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskborderframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskborderframe.setObjectName("maskborderframe")
        self.maskfram = QtWidgets.QFrame(main)
        self.maskfram.setGeometry(QtCore.QRect(410, 5, 281, 241))
        self.maskfram.setStyleSheet("background-color:none;\n"
"image: url(:/images/img2.png);")
        self.maskfram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskfram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskfram.setObjectName("maskfram")
        self.mainbgftame = QtWidgets.QFrame(main)
        self.mainbgftame.setGeometry(QtCore.QRect(0, 85, 890, 560))
        self.mainbgftame.setMinimumSize(QtCore.QSize(890, 560))
        self.mainbgftame.setMaximumSize(QtCore.QSize(890, 560))
        self.mainbgftame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.165, x2:1, y2:0.449, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(1, 29, 63, 255));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.mainbgftame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbgftame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbgftame.setObjectName("mainbgftame")
        self.logoframe_2 = QtWidgets.QFrame(self.mainbgftame)
        self.logoframe_2.setGeometry(QtCore.QRect(0, -40, 231, 191))
        self.logoframe_2.setStyleSheet("image: url(:/images/face recog logo.png);\n"
"background-color:none;")
        self.logoframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoframe_2.setObjectName("logoframe_2")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.mainbgftame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(640, 10, 241, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.timelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.timelabel.setFont(font)
        self.timelabel.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.timelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timelabel.setObjectName("timelabel")
        self.horizontalLayout_9.addWidget(self.timelabel)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.mainbgftame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(640, 80, 241, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.datelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.datelabel.setFont(font)
        self.datelabel.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.datelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datelabel.setObjectName("datelabel")
        self.horizontalLayout_10.addWidget(self.datelabel)
        self.groupBox = QtWidgets.QGroupBox(self.mainbgftame)
        self.groupBox.setGeometry(QtCore.QRect(0, 140, 881, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:none;\n"
"color: rgb(0, 0, 0);\n"
"")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.Submitbutton = QtWidgets.QPushButton(self.groupBox)
        self.Submitbutton.setGeometry(QtCore.QRect(640, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Submitbutton.setFont(font)
        self.Submitbutton.setStyleSheet("QPushButton#Submitbutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Submitbutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#Submitbutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        self.Submitbutton.setCheckable(True)
        self.Submitbutton.setObjectName("Submitbutton")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(50, 20, 49, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.nameEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameEdit.setGeometry(QtCore.QRect(110, 54, 221, 16))
        self.nameEdit.setObjectName("nameEdit")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(350, 20, 91, 79))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(410, 54, 221, 16))
        self.lineEdit.setObjectName("lineEdit")
        self.tableWidget = QtWidgets.QTableWidget(self.mainbgftame)
        self.tableWidget.setGeometry(QtCore.QRect(15, 249, 861, 292))
        self.tableWidget.setMinimumSize(QtCore.QSize(861, 292))
        self.tableWidget.setMaximumSize(QtCore.QSize(861, 292))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"border:1px solid;\n"
"border-top-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"")
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(54, 120, 182))
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(135)
        self.tableWidget.verticalHeader().setDefaultSectionSize(50)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(50)
        self.backbutton = QtWidgets.QPushButton(main)
        self.backbutton.setGeometry(QtCore.QRect(30, 20, 101, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backbutton.sizePolicy().hasHeightForWidth())
        self.backbutton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.backbutton.setFont(font)
        self.backbutton.setStyleSheet("QPushButton#backbutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#backbutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#backbutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("back.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.backbutton.setIcon(icon1)
        self.backbutton.setObjectName("backbutton")
        self.maskborderframe.raise_()
        self.mainbgftame.raise_()
        self.maskfram.raise_()
        self.backbutton.raise_()

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "New Employee"))
        self.label_7.setText(_translate("main", "Time :"))
        self.timelabel.setText(_translate("main", "-"))
        self.label_9.setText(_translate("main", "Date :"))
        self.datelabel.setText(_translate("main", "-"))
        self.groupBox.setTitle(_translate("main", "Details"))
        self.Submitbutton.setText(_translate("main", "Submit"))
        self.label_3.setText(_translate("main", "Name :"))
        self.nameEdit.setPlaceholderText(_translate("main", "Username"))
        self.label_4.setText(_translate("main", "Date :"))
        self.lineEdit.setPlaceholderText(_translate("main", "1400/01/01"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("main", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("main", "Mask"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("main", "Date"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("main", "Clock In"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("main", "Clock Out"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("main", "Total Time"))
        self.backbutton.setText(_translate("main", "BACK"))
import recogapp_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
