# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(800, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.mainbgftame = QtWidgets.QFrame(Dialog)
        self.mainbgftame.setGeometry(QtCore.QRect(100, 110, 500, 400))
        self.mainbgftame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.165, x2:1, y2:0.449, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(1, 29, 63, 255));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.mainbgftame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbgftame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbgftame.setObjectName("mainbgftame")
        self.logoframe_2 = QtWidgets.QFrame(self.mainbgftame)
        self.logoframe_2.setGeometry(QtCore.QRect(0, -40, 231, 191))
        self.logoframe_2.setStyleSheet("image: url(:/images/face recog logo.png);\n"
"background-color:none;")
        self.logoframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoframe_2.setObjectName("logoframe_2")
        self.frame_2 = QtWidgets.QFrame(self.mainbgftame)
        self.frame_2.setGeometry(QtCore.QRect(-30, 130, 601, 421))
        self.frame_2.setStyleSheet("background-color:none;\n"
"border:16px solid  rgb(2, 108, 203);\n"
"\n"
"border-top-left-radius:160px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 210, 371, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"color: rgb(13, 26, 53);")
        self.label.setObjectName("label")
        self.runbutton = QtWidgets.QPushButton(self.frame_2)
        self.runbutton.setGeometry(QtCore.QRect(320, 70, 196, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.runbutton.setFont(font)
        self.runbutton.setStyleSheet("")
        self.runbutton.setObjectName("runbutton")
        self.employeebutton = QtWidgets.QPushButton(self.frame_2)
        self.employeebutton.setGeometry(QtCore.QRect(110, 100, 161, 41))
        self.employeebutton.setStyleSheet("QPushButton#pushButton{\n"
"border:5px ;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(9, 132, 227), stop:1 rgb(170, 166, 157));\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(96, 163, 188), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255)}")
        self.employeebutton.setObjectName("employeebutton")
        self.maskfram = QtWidgets.QFrame(Dialog)
        self.maskfram.setGeometry(QtCore.QRect(470, 30, 250, 250))
        self.maskfram.setStyleSheet("image: url(:/images/img.png);")
        self.maskfram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskfram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskfram.setObjectName("maskfram")
        self.maskborderframe = QtWidgets.QFrame(Dialog)
        self.maskborderframe.setGeometry(QtCore.QRect(470, 30, 250, 250))
        self.maskborderframe.setStyleSheet("border:5px solid  rgb(2, 108, 203);\n"
"background-color: qlineargradient(spread:pad, x1:0.0397727, y1:0.949, x2:0.841, y2:0.159682, stop:0 rgba(1, 29, 63, 176), stop:1 rgba(2, 108, 203, 0));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"")
        self.maskborderframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskborderframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskborderframe.setObjectName("maskborderframe")
        self.maskborderframe.raise_()
        self.mainbgftame.raise_()
        self.maskfram.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Face Recognition Time Attendance App"))
        self.label.setText(_translate("Dialog", "Designed by Melika Mohammadi , Ensieh Shams , Nika NikFetrat"))
        self.runbutton.setText(_translate("Dialog", "Start"))
        self.employeebutton.setText(_translate("Dialog", "New Employee"))
import recogapp_rc
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
