# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(960, 645)
        main.setMinimumSize(QtCore.QSize(960, 645))
        main.setMaximumSize(QtCore.QSize(960, 645))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        main.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main.setWindowIcon(icon)
        main.setStyleSheet("")
        self.maskborderframe = QtWidgets.QFrame(main)
        self.maskborderframe.setGeometry(QtCore.QRect(480, 0, 480, 321))
        self.maskborderframe.setStyleSheet("border:5px solid  rgb(2, 108, 203);\n"
"background-color: qlineargradient(spread:pad, x1:0.0397727, y1:0.949, x2:0.841, y2:0.159682, stop:0 rgba(1, 29, 63, 176), stop:1 rgba(2, 108, 203, 0));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"")
        self.maskborderframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskborderframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskborderframe.setObjectName("maskborderframe")
        self.mainbgftame = QtWidgets.QFrame(main)
        self.mainbgftame.setGeometry(QtCore.QRect(0, 85, 890, 560))
        self.mainbgftame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.165, x2:1, y2:0.449, stop:0 rgba(201, 201, 201, 255), stop:1 rgba(1, 29, 63, 255));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;")
        self.mainbgftame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbgftame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbgftame.setObjectName("mainbgftame")
        self.logoframe_2 = QtWidgets.QFrame(self.mainbgftame)
        self.logoframe_2.setGeometry(QtCore.QRect(0, -40, 231, 191))
        self.logoframe_2.setStyleSheet("image: url(:/images/face recog logo.png);\n"
"background-color:none;")
        self.logoframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoframe_2.setObjectName("logoframe_2")
        self.imgLabel = QtWidgets.QLabel(self.mainbgftame)
        self.imgLabel.setGeometry(QtCore.QRect(30, 160, 500, 299))
        self.imgLabel.setMinimumSize(QtCore.QSize(500, 299))
        self.imgLabel.setMaximumSize(QtCore.QSize(320, 240))
        self.imgLabel.setStyleSheet("border:10px solid  rgb(2, 108, 203);\n"
"border-top-left-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.groupBox = QtWidgets.QGroupBox(self.mainbgftame)
        self.groupBox.setGeometry(QtCore.QRect(590, 160, 291, 361))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 271, 271))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.masklabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.masklabel.setFont(font)
        self.masklabel.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.masklabel.setObjectName("masklabel")
        self.horizontalLayout_5.addWidget(self.masklabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.namelabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.namelabel.setFont(font)
        self.namelabel.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.namelabel.setObjectName("namelabel")
        self.horizontalLayout_4.addWidget(self.namelabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.statuslabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statuslabel.setFont(font)
        self.statuslabel.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.statuslabel.setObjectName("statuslabel")
        self.horizontalLayout_6.addWidget(self.statuslabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.hourslabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hourslabel.setFont(font)
        self.hourslabel.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.hourslabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hourslabel.setObjectName("hourslabel")
        self.horizontalLayout_7.addWidget(self.hourslabel)
        self.minlabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.minlabel.setFont(font)
        self.minlabel.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255,210);")
        self.minlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.minlabel.setObjectName("minlabel")
        self.horizontalLayout_7.addWidget(self.minlabel)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 3, 0, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.mainbgftame)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(640, 10, 241, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.timelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.timelabel.setFont(font)
        self.timelabel.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.timelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timelabel.setObjectName("timelabel")
        self.horizontalLayout_3.addWidget(self.timelabel)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.mainbgftame)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(640, 80, 241, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.datelabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.datelabel.setFont(font)
        self.datelabel.setStyleSheet("background-color: rgb(54, 120, 182);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.datelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.datelabel.setObjectName("datelabel")
        self.horizontalLayout_8.addWidget(self.datelabel)
        self.Clockinbutton = QtWidgets.QPushButton(self.mainbgftame)
        self.Clockinbutton.setEnabled(True)
        self.Clockinbutton.setGeometry(QtCore.QRect(30, 490, 245, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Clockinbutton.setFont(font)
        self.Clockinbutton.setStyleSheet("QPushButton#Clockinbutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Clockinbutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#Clockinbutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        self.Clockinbutton.setCheckable(True)
        self.Clockinbutton.setObjectName("Clockinbutton")
        self.Clockoutbutton = QtWidgets.QPushButton(self.mainbgftame)
        self.Clockoutbutton.setGeometry(QtCore.QRect(280, 490, 245, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Clockoutbutton.setFont(font)
        self.Clockoutbutton.setStyleSheet("QPushButton#Clockoutbutton{\n"
"border:5px ;\n"
"    background-color: rgb(2, 108, 203);\n"
"color: rgb(255, 255, 255,210);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#Clockoutbutton:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgb(52, 73, 98), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"QPushButton#Clockoutbutton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(150,123,111,255);}")
        self.Clockoutbutton.setCheckable(True)
        self.Clockoutbutton.setObjectName("Clockoutbutton")
        self.maskfram = QtWidgets.QFrame(main)
        self.maskfram.setGeometry(QtCore.QRect(410, 0, 281, 241))
        self.maskfram.setStyleSheet("background-color:none;\n"
"image: url(:/images/img2.png);")
        self.maskfram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskfram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskfram.setObjectName("maskfram")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Authentication"))
        self.groupBox.setTitle(_translate("main", "Details"))
        self.label_2.setText(_translate("main", "Mask :"))
        self.masklabel.setText(_translate("main", "-"))
        self.label_3.setText(_translate("main", "Name :"))
        self.namelabel.setText(_translate("main", "-"))
        self.label_8.setText(_translate("main", "Status :"))
        self.statuslabel.setText(_translate("main", "-"))
        self.label_6.setText(_translate("main", "Total Time :"))
        self.hourslabel.setText(_translate("main", "-"))
        self.minlabel.setText(_translate("main", "-"))
        self.label_4.setText(_translate("main", "Time :"))
        self.timelabel.setText(_translate("main", "-"))
        self.label_9.setText(_translate("main", "Date :"))
        self.datelabel.setText(_translate("main", "-"))
        self.Clockinbutton.setText(_translate("main", "Clock In"))
        self.Clockoutbutton.setText(_translate("main", "Clock Out"))
import recogapp_rc
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QDialog()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
