# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trainingwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie

class Ui_Trainingwindow(object):
    def setupUi(self, Trainingwindow):
        Trainingwindow.setObjectName("Trainingwindow")
        Trainingwindow.resize(500, 480)
        Trainingwindow.setMinimumSize(QtCore.QSize(500, 480))
        Trainingwindow.setMaximumSize(QtCore.QSize(500, 480))
        self.maskborderframe = QtWidgets.QFrame(Trainingwindow)
        self.maskborderframe.setGeometry(QtCore.QRect(0, 80, 500, 400))
        self.maskborderframe.setStyleSheet("border:5px solid  rgb(2, 108, 203);\n"
"background-color: qlineargradient(spread:pad, x1:0.0397727, y1:0.949, x2:0.841, y2:0.159682, stop:0 rgba(1, 29, 63, 176), stop:1 rgba(2, 108, 203, 0));\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"")
        self.maskborderframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskborderframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskborderframe.setObjectName("maskborderframe")
        self.label = QtWidgets.QLabel(self.maskborderframe)
        self.label.setGeometry(QtCore.QRect(200, 290, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"background-color:none;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Loading = QtWidgets.QLabel(self.maskborderframe)
        self.Loading.setGeometry(QtCore.QRect(163, 100, 300, 200))
        self.Loading.setStyleSheet("background-color:none;\n"
"border:none;")
        self.movie = QMovie("loading6.gif")
        self.Loading.setMovie(self.movie)
        self.movie.start()
        self.Loading.setObjectName("Loading")
        self.maskfram = QtWidgets.QFrame(Trainingwindow)
        self.maskfram.setGeometry(QtCore.QRect(110, -20, 281, 241))
        self.maskfram.setStyleSheet("background-color:none;\n"
"image: url(:/images/img.png);")
        self.maskfram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.maskfram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.maskfram.setObjectName("maskfram")

        self.retranslateUi(Trainingwindow)
        QtCore.QMetaObject.connectSlotsByName(Trainingwindow)

    def retranslateUi(self, Trainingwindow):
        _translate = QtCore.QCoreApplication.translate
        Trainingwindow.setWindowTitle(_translate("Trainingwindow", "Training"))
        self.label.setText(_translate("Trainingwindow", "Training . . ."))
        
import recogapp


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Trainingwindow = QtWidgets.QWidget()
    ui = Ui_Trainingwindow()
    ui.setupUi(Trainingwindow)
    Trainingwindow.show()
    sys.exit(app.exec_())
